POST  http://localhost:8000/user?user_id=1&first_name=Alizhanslda HTTP/1.1
content-type: application/json

{
    "user_id": 1,
    "first_name": "Test"
}
###

GET http://localhost:8000/user/askj HTTP/1.1
content-type: application/json


###

PUT http://localhost:8000/user/updatePhone HTTP/1.1
content-type: application/json

{
    "biin": "7",
    "phone": "Robert"
} 
###
GET http://localhost:8000/currency/save?date=15.03.2022 HTTP/1.1

###
GET http://localhost:8000/currency/save?date=15.03.2022&code=AZN HTTP/1.1


